#!/bin/bash
set -euo pipefail
set -x

export SKYSCRAPER_HOME="$(cd "$(dirname "$0")/../.." && pwd)"
source "${SKYSCRAPER_HOME}/supplementary/workflows/core.sh"

cleanup() {
   mv VERSION.bk VERSION.ini &>/dev/null || true
}

cleanup

run_termux_docker() {
   local -r arch="$1"

   "./termux-packages/scripts/run-docker.sh" ./build-package.sh -a "$arch" -I "$PKG_NAME"

   rm -rf target || true
   mkdir -p target || true
   docker cp "termux-package-builder:/data/data/com.termux/files/usr/bin/${PKG_BIN_NAME}" "target"
}

build() {
   source "VERSION.ini"
   LATEST="$VERSION"

   if [[ "$OSTYPE" == *"arwin"* ]]; then
      mv VERSION.ini VERSION.bk || true
   fi

   cd "$SKYSCRAPER_HOME"
   # Qt5
   make --ignore-errors distclean || true
   sed -ie "0,/CONFIG += /{s/CONFIG.*/CONFIG += debug/}" skyscraper.pro
   qmake
   jobs=$(getconf _NPROCESSORS_ONLN 2>/dev/null || sysctl -n hw.ncpu)
   make "-j$jobs"
   sudo make install
   # Qt6, without make install
   make --ignore-errors distclean || true
   sed -ie "0,/CONFIG += /{s/CONFIG.*/CONFIG += release/}" skyscraper.pro
   qmake6
   make "-j$jobs"
}

main() {
   case "${1:-}" in
      "android-aarch64") run_termux_docker "aarch64" ;;
      "android-arm") run_termux_docker "arm" ;;
      *) build ;;
   esac
}

trap cleanup EXIT
main "$@"
